on:
  push:
    branches:
      - release

jobs:

  job-one:
    name: Build, push, deploy and update digital Ocean
    runs-on: ubuntu-latest
    steps:

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RSA_KEY_DOCEAN_PRIVATE_SECRET }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H 164.92.71.78  >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build --if-present
      - run: |
          echo "npm run build FINISHED!!!"
          ls -la

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 164.92.71.78
          username: root
          key: ${{ secrets.RSA_KEY_DOCEAN_PRIVATE_SECRET }}
          port: 22
          source: "./dist/"
          target: "/usr/share/nginx/html"

      - name: Connect to Digital Ocean via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 164.92.71.78
          username: root
          key: ${{ secrets.RSA_KEY_DOCEAN_PRIVATE_SECRET }}
          port: 22
          command_timeout: 1m
          script: |
            pwd
            tree /usr/share/nginx/html/dist
            sudo systemctl restart nginx
            sudo systemctl status nginx